# Generated by Django 5.1.7 on 2025-05-17 15:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('order_created', 'Order Created'), ('order_confirmed', 'Order Confirmed'), ('order_processing', 'Order Processing'), ('order_ready', 'Order Ready'), ('order_shipped', 'Order Shipped'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('payment_success', 'Payment Success'), ('payment_failed', 'Payment Failed'), ('stock_low', 'Low Stock Alert'), ('general', 'General Notification')], default='general', max_length=30)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='pharmacys_n_recipie_784e71_idx'), models.Index(fields=['recipient', 'created_at'], name='pharmacys_n_recipie_5008d0_idx'), models.Index(fields=['type'], name='pharmacys_n_type_da4755_idx')],
            },
        ),
    ]
