# Generated by Django 5.1.7 on 2025-05-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacys', '0002_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
