# Generated by Django 5.1.7 on 2025-05-21 21:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacys', '0003_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='purchase_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
