# Generated by Django 5.1.7 on 2025-05-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacys', '0004_stockbatch_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
