# Generated by Django 5.1.7 on 2025-05-22 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacys', '0005_stockbatch_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbatch',
            name='purchase_date',
        ),
    ]
