# Generated by Django 5.1.7 on 2025-05-22 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacys', '0006_remove_stockbatch_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbatch',
            name='purchase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
