# Generated by Django 5.1.7 on 2025-05-16 19:32

import apps.ehr.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment', '0002_timeoff_is_approved_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chief_complaint', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('is_locked', models.BooleanField(default=False, help_text='Locked when appointment is completed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_record', to='appointment.appointment')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL)),
                ('previous_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_records', to='ehr.medicalrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.ehr.models.medical_attachment_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('LAB_REPORT', 'Lab Report'), ('IMAGING', 'Imaging/Scan'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other Document')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_attachments', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ehr.medicalrecord')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('VIEW', 'Viewed'), ('EXPORT', 'Exported'), ('LOCK', 'Locked')], max_length=50)),
                ('field_modified', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ehr.medicalrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_record_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('fulfillment_status', models.CharField(choices=[('UNFULFILLED', 'Unfulfilled'), ('FULFILLED_HERE', 'Fulfilled at Our Pharmacy'), ('FULFILLED_ELSEWHERE', 'Fulfilled Elsewhere')], default='UNFULFILLED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='ehr.medicalrecord')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['appointment'], name='ehr_medical_appoint_899bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_at'], name='ehr_medical_created_4cfc65_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['created_by'], name='ehr_medical_created_9337ef_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordaudit',
            index=models.Index(fields=['medical_record'], name='ehr_medical_medical_001f08_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordaudit',
            index=models.Index(fields=['timestamp'], name='ehr_medical_timesta_245c9b_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecordaudit',
            index=models.Index(fields=['performed_by'], name='ehr_medical_perform_940b35_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['fulfillment_status'], name='ehr_prescri_fulfill_ad8bfe_idx'),
        ),
    ]
