# Generated by Django 5.1.7 on 2025-05-18 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['medication']},
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='ehr_prescri_fulfill_ad8bfe_idx',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='fulfillment_status',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='quantity',
        ),
    ]
