# Generated by Django 5.1.7 on 2025-04-27 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_medicalrecord_previous_record'),
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medication',
        ),
        migrations.AddField(
            model_name='prescription',
            name='fulfillment_status',
            field=models.CharField(choices=[('UNFULFILLED', 'Unfulfilled'), ('FULFILLED_HERE', 'Fulfilled at Our Pharmacy'), ('FULFILLED_ELSEWHERE', 'Fulfilled Elsewhere')], default='UNFULFILLED', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medicine',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prescriptions', to='pharmacy.medicine'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['medicine'], name='ehr_prescri_medicin_6e2583_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['fulfillment_status'], name='ehr_prescri_fulfill_ad8bfe_idx'),
        ),
    ]
