# Generated by Django 5.1.7 on 2025-05-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ehr', '0002_alter_prescription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed')], default='PROCESSING', help_text='Status of the medical record', max_length=20),
        ),
    ]
